<?php
require($_SERVER['SITE_ROOT'] . '/framework/loader.php');
BeaconTemplate::SetTitle('Troubleshooting');
?><h1>Getting Started</h1>
<div class="indent">
	<p>New users who have no idea how to start customizing loot should <a href="gettingstarted.php">read this</a>.</p>
</div>
<h1>Troubleshooting</h1>
<div class="indent">
	<p>As much as Beacon attempts to be self-explaining, sometimes there are problems that require human interaction.</p>
	<h3>Engrams are not updating</h3>
	<div class="indent">
		<p>Beacon automatically updates its engram database every launch. However, there are scenarios that could prevent this from happening.</p>
		<p>First thing is first, manually update your engrams. <a href="/download/classes.php">Download the engrams</a>, then use &quot;Import&hellip;&quot; from the &quot;File&quot; menu to import the file into Beacon.</p>
		<p>Now on to actually solving the problem. Users on Windows 7 and Windows 8.0 (but not Windows 8.1 and newer) often have this issue because these versions do not have support for TLS 1.1 and 1.2 enabled, which Beacon requires. Normally, the Beacon installer will attempt to enable this support automatically, but this doesn't always work.</p>
		<p>See <a href="https://support.microsoft.com/en-gb/help/3140245/update-to-enable-tls-1.1-and-tls-1.2-as-a-default-secure-protocols-in-winhttp-in-windows">https://support.microsoft.com/en-gb/help/3140245/update-to-enable-tls-1.1-and-tls-1.2-as-a-default-secure-protocols-in-winhttp-in-windows</a> for more details and a solution.</p>
	</div>
	<h3>The ini file produced isn't what was expected</h3>
	<div class="indent">
		<p>This is such a detailed subject that there is <a href="math.php">an entire separate page</a> just explaining how Beacon does its math. Though the short version of the story is that Beacon produces ini files intended for Ark to read them, not humans. The code it creates attempts to tell Ark about the author's intentions. This means sometimes doing weird things to make that a reality.</p>
	</div>
	<h3 id="exportformat">How do I choose an export format?</h3>
	<div class="indent">
		<p>It is possible for multiple mods to define the same class string, which confuses Ark's loot generator, so Beacon uses blueprints to solve the issue. This is the &quot;More Reliable&quot; option.</p>
		<p>However, the option to use blueprints was never explained in the original forum post describing the <em>ConfigOverrideSupplyCrateItems</em> config option. Some mods define their own loot sources and may not be able to understand blueprints. When this happens, Ark tends to crash at launch. Switching to &quot;More Compatible&quot; in this scenario will export using classes, but may produce unexpected results if there are conflicts.</p>
	</div>
	<h3>Learning more about ConfigOverrideSupplyCrateItems</h3>
	<div class="indent">
		<p>See <a href="spec.php">this document</a> for more details about what Beacon knows about the ConfigOverrideSupplyCrateItems config option.</p>
	</div>
	<h3>Loot sources not updating on official maps.</h3>
	<div class="indent">
		<p>The loot override code generated by Beacon is recognized by Ark, but not yet by some other tools. Users of Ark Server Manager have reported issues using the code that Beacon generates. Update to Ark Server Manager 1.0.288 (or newer) and disable Supply Crate Overrides. This will prevent ASM from altering the code that Beacon generates.</p>
	</div>
	<h3>Some more personal help</h3>
	<div class="indent">
		<p>Get in touch. Bugs should be reported on the <a href="/reportaproblem.php">GitHub page</a>. Anybody can create an account and this is more helpful than email when it comes to bugs. General help inquiries should be sent to <a href="mailto:forgotmyparachute@beaconapp.cc">forgotmyparachute@beaconapp.cc</a>.</p>
		<p class="text-center"><a href="https://discord.gg/2vbT7fV"><img height="40" src="/assets/images/discord-full-white.svg"></a></p>
		<p>Beacon now has a <a href="https://discord.gg/2vbT7fV">Discord server</a>. Come ask questions, but realize that people need to sleep.</p>
	</div>
</div>